# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/ofdm_transreceiver_clock.xdc

# XDC: imports/sysgen/ofdm_transreceiver.xdc

# Block Designs: bd/ofdm_transreceiver_bd/ofdm_transreceiver_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_transreceiver_bd || ORIG_REF_NAME==ofdm_transreceiver_bd} -quiet] -quiet

# IP: bd/ofdm_transreceiver_bd/ip/ofdm_transreceiver_bd_ofdm_transreceiver_1_0/ofdm_transreceiver_bd_ofdm_transreceiver_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_transreceiver_bd_ofdm_transreceiver_1_0 || ORIG_REF_NAME==ofdm_transreceiver_bd_ofdm_transreceiver_1_0} -quiet] -quiet

# XDC: c:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.gen/sources_1/bd/ofdm_transreceiver_bd/ofdm_transreceiver_bd_ooc.xdc
