# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.srcs/sources_1/ip/ofdm_transreceiver_0/ofdm_transreceiver_0.xci
# IP: The module: 'ofdm_transreceiver_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.gen/sources_1/ip/ofdm_transreceiver_0/ofdm_transreceiver_xfft_v9_1_i0/ofdm_transreceiver_xfft_v9_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_transreceiver_xfft_v9_1_i0 || ORIG_REF_NAME==ofdm_transreceiver_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.gen/sources_1/ip/ofdm_transreceiver_0/constrs/ofdm_transreceiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_transreceiver_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.srcs/sources_1/ip/ofdm_transreceiver_0/ofdm_transreceiver_0.xci
# IP: The module: 'ofdm_transreceiver_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.gen/sources_1/ip/ofdm_transreceiver_0/ofdm_transreceiver_xfft_v9_1_i0/ofdm_transreceiver_xfft_v9_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_transreceiver_xfft_v9_1_i0 || ORIG_REF_NAME==ofdm_transreceiver_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/Gokaraan/Documents/Composer/OFDM/HDL/ip_catalog/ofdm_transreceiver.gen/sources_1/ip/ofdm_transreceiver_0/constrs/ofdm_transreceiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_transreceiver_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
